PXLFunds/PXLFunds/Controllers/UserFundsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PXLFunds.Data;

namespace PXLFunds.Controllers
{
    public class UserFundsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserFundsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: UserFunds
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.UserFund.Include(u => u.Fund);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: UserFunds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userFund = await _context.UserFund
                .Include(u => u.Fund)
                .FirstOrDefaultAsync(m => m.UserFundId == id);
            if (userFund == null)
            {
                return NotFound();
            }

            return View(userFund);
        }

        // GET: UserFunds/Create
        public IActionResult Create()
        {
            ViewData["FundId"] = new SelectList(_context.Fund, "FundId", "FundId");
            return View();
        }

        // POST: UserFunds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserFundId,UserId,FundId,Amount")] UserFund userFund)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userFund);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FundId"] = new SelectList(_context.Fund, "FundId", "FundId", userFund.FundId);
            return View(userFund);
        }

        // GET: UserFunds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userFund = await _context.UserFund.FindAsync(id);
            if (userFund == null)
            {
                return NotFound();
            }
            ViewData["FundId"] = new SelectList(_context.Fund, "FundId", "FundId", userFund.FundId);
            return View(userFund);
        }

        // POST: UserFunds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserFundId,UserId,FundId,Amount")] UserFund userFund)
        {
            if (id != userFund.UserFundId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userFund);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserFundExists(userFund.UserFundId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FundId"] = new SelectList(_context.Fund, "FundId", "FundId", userFund.FundId);
            return View(userFund);
        }

        // GET: UserFunds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userFund = await _context.UserFund
                .Include(u => u.Fund)
                .FirstOrDefaultAsync(m => m.UserFundId == id);
            if (userFund == null)
            {
                return NotFound();
            }

            return View(userFund);
        }

        // POST: UserFunds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userFund = await _context.UserFund.FindAsync(id);
            _context.UserFund.Remove(userFund);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserFundExists(int id)
        {
            return _context.UserFund.Any(e => e.UserFundId == id);
        }

    }
}

PXLFunds/PXLFunds/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PXL Funds</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="row bg-dark text-center">
            <div class="col-2 text-right text-white">
                Pxl Fund
            </div>
            <div class="col-1 text-right">
            </div>
            <div class="col-5 text-center">
                <a class="text-white" asp-area="" asp-controller="Bank" asp-action="Index">Bank Info</a>
                &nbsp;
                <a class="text-white" asp-area="" asp-controller="Fund" asp-action="Index">Fund Info</a>
            </div>
            <div class="col-4 text-right">
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="text-white" asp-area="" asp-controller="UserFunds" asp-action="Index">Mijn fondsen</a>
                    <a class="text-white" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                }
                else
                {
                    <a class="text-white" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                    <a class="text-white" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                }
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
           
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>